=== Nicovidal2002/MarkupEV2/XML-VALIDATION DU4/xsd-try/company.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="company">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="generalInfo" type="GeneralInfoType" />
                <xs:element name="DepStaff">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="employers">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="employee" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="nameAndSurname"
                                                        type="xs:string" />
                                                    <xs:element name="role" type="xs:string" />
                                                    <xs:element name="sickLeave" type="xs:string" />
                                                    <xs:element name="salary" type="xs:string" />
                                                    <xs:element name="key" type="xs:string" />
                                                </xs:sequence>
                                                <xs:attributeGroup ref="attGroup" />
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="date" use="required" type="xs:date" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="Multinacional" use="required" />
            <xs:attribute name="Currency" type="xs:string" fixed="Euro" />
        </xs:complexType>
    </xs:element>

    <xs:attributeGroup name="attGroup">
        <xs:attribute name="code" use="required" />
        <xs:attribute name="DepName" use="required" />
        <xs:attribute name="user" use="required" />
    </xs:attributeGroup>

    <xs:complexType name="GeneralInfoType">
        <xs:sequence>
            <xs:element name="name" type="xs:string" />
            <xs:element name="numberOfEmployees" type="xs:integer" minOccurs="1"/>
            <xs:element name="sector">
                <xs:complexType>
                    <xs:sequence>
                        <xs:choice>
                            <xs:element name="education" />
                            <xs:element name="finances" />
                            <xs:element name="technology" />
                        </xs:choice>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="textType">
        <xs:restriction base="xs:string">
            <xs:minLength value="1" />
            <xs:maxLength value="40" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Nicovidal2002/MarkupEV2/XML-VALIDATION DU4/xsd-try/company.xml
<company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="company.xsd" Multinacional="NO" Currency="Euro">
    <generalInfo>
        <name>XML Technologies</name>
        <numberOfEmployees>6</numberOfEmployees>
        <sector><technology/></sector>
    </generalInfo>
    <DepStaff date="2023-03-02">
        <employers>
            <employee code="ADMIN" DepName="Administration" user="atorres">
                <nameAndSurname>Alicia Torres Pan</nameAndSurname>
                <role>head of department</role>
                <sickLeave>NO</sickLeave>
                <salary>2250.00</salary>
                <key>3%abYki6</key>
            </employee>
            <employee code="ADMIN" DepName="Administration" user="xaldrei">
                <nameAndSurname>Xoán Aldrei Soto</nameAndSurname>
                <role>Employee</role>
                <sickLeave>YES</sickLeave>
                <salary>1200.00</salary>
                <key>6@hjKm87</key>
            </employee>
            <employee code="ADMIN" DepName="Administration" user="amotar">
                <nameAndSurname>Ana Mota Rei</nameAndSurname>
                <role>Employee</role>
                <sickLeave>NO</sickLeave>
                <salary>1250.50</salary>
                <key>4%wtrtHQ</key>
            </employee>
            <employee code="COMPU" DepName="Computer" user="obaltar">
                <nameAndSurname>Óscar Baltar Dacosta</nameAndSurname>
                <role>Head of department</role>
                <sickLeave>YES</sickLeave>
                <salary>2300.75</salary>
                <key>8$abcdHj
                </key>
            </employee>
            <employee code="COMPU" DepName="Computer" user="hvilar">
                <nameAndSurname>Helena Vilar Moure</nameAndSurname>
                <role>Employee</role>
                <sickLeave>NO</sickLeave>
                <salary>1500.35</salary>
                <key>9?sdKp:s</key>
            </employee>
            <employee code="MARKE" DepName="Marketing" user="guest">
                <nameAndSurname>Andrea Serodio Paz</nameAndSurname>
                <role>Head of department</role>
                <sickLeave>NO</sickLeave>
                <salary>2500.85</salary>
                <key>2$xlzhYH</key>
            </employee>
        </employers>
    </DepStaff>
</company>
