=== Nicovidal2002/MarkupEV2/XML-VALIDATION DU4/xsd-try/items.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Items">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Item" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="photo" type="xs:string"/>
                            <xs:element name="tags" type="xs:string"/>
                            <xs:element name="diameter" type="xs:decimal"/>
                            <xs:element name="weight" type="xs:decimal"/>
                            <xs:element name="price" type="xs:decimal"/>
                            <xs:element name="size" type="SizeType" minOccurs="0"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="SizeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Big"/>
            <xs:enumeration value="Small"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Nicovidal2002/MarkupEV2/XML-VALIDATION DU4/xsd-try/items.xml
<?xml version="1.0" encoding="UTF-8"?>
<Items xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="items.xsd">
    <Item>
        <name>Item 1</name>
        <photo></photo>
        <tags></tags>
        <diameter>0</diameter>
        <weight>0</weight>
        <price>0</price>
        <size>Small</size>
    </Item>
    <Item>
        <name>Item 1</name>
        <photo></photo>
        <tags></tags>
        <diameter>0</diameter>
        <weight>0</weight>
        <price>0</price>
        <size>Small</size>
    </Item>
    <Item>
        <name>Item 1</name>
        <photo></photo>
        <tags></tags>
        <diameter>0</diameter>
        <weight>0</weight>
        <price>0</price>
        <size>Small</size>
    </Item>
</Items>
